### ISSUE TITLE
FTL console does not re-populate module that is stopped then redeployed during `ftl dev`

### ISSUE THREAD

**Issue by mistermoe** [TBD54566975/ftl#1200]
https://github.com/TBD54566975/ftl/assets/4887440/e5c149f7-f38a-4819-8559-a21550fa397e

**Comment by wesbillman** [comment]
I think this issue was introduced here: https://github.com/TBD54566975/ftl/pull/1172/files#diff-a0c459862b79adf4314734937ce8e1e95f29f39932687ee3e879fff6e6bb214c

Because of the way the schema changes and deployments work, when we detect a schema change in the db, it will have been caused by a deployment record being created or updated. However, at this time the runners might not have reconciled. So we'll have a deployment with `min_replicas > 0` but no runner assigned yet. And because we use `PullSchema` to detect when changes have occurred this results in only deployments which have fully reconciled being returned.

I'll make a PR with a new `dal` method to get deployments with replicas, but we might want to discuss if that is the best approach here as well.
