### ISSUE TITLE
buildengine can reach a deadend where build errors can't be easily fixed by user

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#1211]
Steps to repro:
- start `ftl dev` with 2 modules, lets call them moduleA and moduleB
- in moduleA, create a verb and call it `VerbA`
- in moduleB, make a call to to the verb `moduleA.VerbA`
    - ftl autodetects the change and deploys both modules
- update moduleB to call modulaA.VerbB (even though it doesnt exist)
    - ftl autodetects the change and tries to build moduleB but fails. This is expected
- update moduleA's verb to be called VerbB instead of VerbA
    - ftl autodetects the change and tries to build moduleA and succeeds.
    - ftl then tries to deploy moduleA and fails:
 > error:controller0: Invalid module schema: invalid schema: .../moduleB/moduleB.go:29:16-16: unknown reference "moduleA.verbA"

The user can't really do much to untie this knot. Editing moduleB in small ways keeps failing with unknown reference for verbB. updating modulaA fails because a deployed module refers to verbA
- terminating ftl dev and rerunning it fixes the issue

**Comment by wesbillman** [comment]
Great repro steps @matt2e!!!

Took a quick look at this one and we're hitting this validation error, which makes sense since the whole schema won't validate with calls to unknown types. 
https://github.com/TBD54566975/ftl/blob/main/backend/schema/validate.go#L126-L128

Removing that check makes everything deploy correct, but leaves us open to deploying invalid schema so we'll probably need a more robust solution
