### ISSUE TITLE
We need to figure out a way to register sum types for the current module under `ftltest`

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1577]
Currently sum types for the current module are only registered in the codegenned `main`. Unfortunately during tests, this module is never executed and thus the types will not be registered under `ftltest`. Off the top of my head I can't think of a great solution to this. We could perahps register the main module's types in every codegenned external module, but if the main module doesn't import any external modules this won't work. Needs more thinking.

cc @deniseli @matt2e

**Comment by matt2e** [comment]
Brainstorming:

Idea A:
Instead of codegen-ing it into `main.go` could we write it out as json to a path somewhere in `_ftl/`, and make main.go read it, and `ftltest.Context()` read it
- Is the problem with this that it's hard for us to go from json to the real types?

Idea B:
Could we do the same as Idea A but with a subpackage rather than a json file?
- But is the problem here that ftltest can't import a package that is relative to the module path?

**Comment by alecthomas** [comment]
It's actually already written by the build as a protobuf, but yeah the problem is there's no real tie between the schema type and the Go type. Maybe we could do that at runtime in `ftltest` though...

**Comment by alecthomas** [comment]
The problem is that the code (currently) needs to be codegenned into somewhere and must be imported so that it can be registered.

Another option could be to codegen a file into the root of the module alongside the user code, but that feels pretty gross.

**Comment by alecthomas** [comment]
Was thinking a bit more about this, and maybe the solution is to just not do anything - what I mean by that is that when we encounter a field that is an interface, we just assume it's a sum type and encode the value accordingly, and let the schema extraction take care of any validation/errors. I'm not 100% sure this will work, WDYT @deniseli ?

**Comment by deniseli** [comment]
Leaving my in-progress notes here to track all the less-than-ideal nuances of assuming all interface values are sumtypes. If at any point there's something that's too big of a trade-off for us to accept, and we can't come up with an alternative, then we can pull the plug.

1. For `Marshal`: We currently look up the sumtype in the type registry just to get the name of the sumtype discriminator. For now, I hardcoded "AnonymousSumTypeVariant" as the name, so the output JSON will look like: `{"d":{"name":"AnonymousSumTypeVariant","value":{...}}}` rather than having the actual variant name under `"name"`. There's probably a way to get the actual Go struct name from the to-be-encoded value itself, so I'll try to get that working.

1. For `Unmarshal`: Currently, encoding.go's Unmarshal works like this:
```go
variantType, ok := reflection.GetVariantByName(v.Type(), sumType.Name).Get()
if !ok {
	return fmt.Errorf("no enum variant found by name %s", sumType.Name)
}

out := reflect.New(variantType)
err := decodeValue(json.NewDecoder(bytes.NewReader(sumType.Value)), out.Elem())
```
_src: https://github.com/TBD54566975/ftl/blob/main/go-runtime/encoding/encoding.go#L404_

If we remove that `!ok` check, then `Unmarshal` wouldn't be able to construct the specific, correct inner struct for the variant, and correspondingly, `out.Elem()` would not have the matching type. I'm currently trying this out with `any`, `interface{}`, and `map` to see if any of those can give a decent alternative.

3. Assuming all of the above pans out, I want to also think about some other potential use cases for interfaces/methods in the go-runtime code to make sure the assumption itself isn't an issue.

4. Do we plan on adding any more typeregistry registrations to `main.go`, other than sumtypes? i.e. is making this workaround for sumtype sufficient or are there other sorts of registrations we'll need to find workarounds for in the future?

**Comment by deniseli** [comment]
Update: pending discussion, I'm going to put this on pause / admit defeat. Unmarshaling is the issue.

I tried two potential approaches for unmarshaling in the absence of a variant type:
1. `variantType = v.Type()` (i.e. the discriminator's type) is not actually compatible with the json decoder, which makes sense because the discriminator doesn't provide any of the necessary fields names/types to unmarshal into. We can only get that from the variant type.
2. `variantType = reflect.TypeFor[any]()` works up to a point: it can decode what was once a struct, via json, into a map. For example, `variant{message: "hello"}` when typed as an `any` decodes into `map[message:hello]`. This does successfully extract the data, but not in the correct type, or even a close-enough type that could be cast into the variant type by downstream code.

On the bright side, encoding works perfectly even in the absence of the registry, so if anyone can think of a solution for decoding, I can reprise my branch and finish this up. If not, we'll probably want to choose a solution where we actually codegen the registrations somewhere.

For now, I'll set this down and pull another issue off `next`.

**Comment by alecthomas** [comment]
Want to push up your WiP branch so we don't lose it when we resume work?

**Comment by deniseli** [comment]
Good idea - done: https://github.com/TBD54566975/ftl/pull/1619

**Comment by alecthomas** [comment]
I've been thinking a bit more about this, and I think we will still want this to work @deniseli , otherwise `ftl-runtime/encoding` won't be usable at all.

**Comment by deniseli** [comment]
Good point - I completely forgot about users calling `encoding` explicitly from a test. If we add something like `ftltest.RegisterSumTypes()` that could work, but it's annoying that users would need to know to do that. On the other hand, I can't think of a way to invoke the registration code without some sort of explicit call in the unit test. Do you think it would be too gross to modify the error message in `encoding` to suggest calling `ftltest.RegisterSumTypes()`? It would be great if `encoding` could know that it's being called in a testing environment, but Marshal/Unmarshal don't take a `context` arg, so I can't think of a good workaround.

**Comment by alecthomas** [comment]
Didn't your codegen into the package code work?

**Comment by deniseli** [comment]
Oh good point - I don't know how I forgot that would also work for encoding. I'll add some tests to make sure it all WAI in the morning and send out the PR.
