### ISSUE TITLE
Workaround for sum type registration in current module

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1792]
We've had a few different ideas, but none seem to work. For example we could codegen into `_ftl/go/main`, but this directory is not linked in during tests. We also attempted to do it dynamically, but during unmarshalling there's no association between the sum type interface and its variants.

<s>Currently there's no way to register sum types for the module being built. As a workaround, let's codegen some Go code into the module itself that performs this registration.  It would go into [this](https://github.com/TBD54566975/ftl/tree/main/go-runtime/compile/build-template) path, called something obvious like `ftl_types.go`.

One downside is that when the user modifies their sum types, the code will fail to compile. We might need to skip this file during type analysis, so that it will get regenerated automatically without the user having to make any changes themselves.</s>

I realised the above won't work when running tests in subpackages as the subpackage may not import the root package. We could instead generate the code for sum types in the same package as the sum type is defined, though it still has the other issues above. Something to keep in mind, but I think there's a "better" way, described below.

What _will_ work is using a [dynamically loaded plugin](https://pkg.go.dev/plugin). When building the module:

1. Add registration code for sum types in the main module to `_ftl/go/main` (may already be doing this?) - this will be statically linked during normal compilation, avoiding the need for plugins.
2. Generate + build a plugin in `_ftl/go/main/types`. This also registers the types from the main module, but is only used in tests.
3. Update the `ftltest` package to load the plugin. Loading the plugin runs `init()`, which registers the types.

Unfortunately plugins are only available on Linux and Mac, but for now those are our target platforms. Eventually if we do support Windows we can fall back on generating the registration code alongside the types.

**Comment by deniseli** [comment]
Update:

The plugin idea was a bust because we couldn't get `plugin.Open` to stop erroring on version mismatch: `panic: plugin.Open("./_ftl/types"): plugin was built with a different version of package ftl/sumtypes`. Since the plugin approach was a bit gross from a dev flow perspective anyway, we're transitioning to plan B: registering the sumtype variants in the module package itself:

```
mymodule/
    mymodule.go   <- user code
    types.ftl.go  <- generated type registrations
```

This will need a bit more work to support sumtypes in submodules later, after we support declaring type enums in subpackages by migrating them to the new extractor. In the meantime, I'll just build this for the top level package in the module. After the sumtype extractor migration, we can carry this change forward to work on the subpackages.
