### ISSUE TITLE
Now seeing lots of "context canceled" warnings when a module is reloaded during `ftl dev`

### ISSUE THREAD

**Issue by alecthomas** [TBD54566975/ftl#1956]
This only started happening quite recently, I'm not sure why.

```
warn:runner13: Failed to close stream: canceled: Post "http://localhost:8892/xyz.block.ftl.v1.ControllerService/StreamDeploymentLogs": context canceled
warn:runner13: Failed to close stream: canceled: Post "http://localhost:8892/xyz.block.ftl.v1.ControllerService/RegisterRunner": context canceled
```

**Comment by gak** [comment]
It was due to fixing a lint of an error that might have intentionally been ignored in the first place: https://github.com/TBD54566975/ftl/commit/9941e4b57373ff0ec480819223bdf57c225b40e6#diff-480fd9ed6d8c8de5875599656b26df5b9d0eca860e33d983b1a151d9337780bbL178

I suspect it is ignored because the connection actually should already be closed, but might need clarification @alecthomas 

Going to set the log level to Debug rather that revert the change so we can see the error if we need to debug further.

**Comment by alecthomas** [comment]
I think logging it at debug is the right call 👍
