### ISSUE TITLE
ASM tests are flaky

### ISSUE THREAD

**Issue by matt2e** [TBD54566975/ftl#2092]
logs: https://github.com/TBD54566975/ftl/actions/runs/9967125333/job/27540391199?pr=2091

**Comment by matt2e** [comment]
Another https://github.com/TBD54566975/ftl/actions/runs/9967731783/job/27541843898?pr=2093

**Comment by matt2e** [comment]
Looks like this issue again: https://github.com/TBD54566975/ftl/issues/1368#issuecomment-2087944187

**Comment by stuartwdouglas** [comment]
I think this is due to a race in the clock library: https://github.com/benbjohnson/clock/blob/b675fcb0bb3e3b2ccd209a1d2dfbd9a00079ec37/clock.go#L176

It selects the next timer to tick then releases the lock, which means two goroutines can Tick the same timer. The second one will block forever as the channel has a size of 1 and the routine holds the lock nothing can read from the channel.
