### ISSUE TITLE
Add Playwright tests to console.

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#2416]
We should try to use [Playwright](https://playwright.dev/) to run tests against a running ftl dev command

I think this can be do manually by running `npx playwright test` while `ftl dev` is running.
We can also make this an integration test which fires up and deploys a couple modules (probably `time` and `echo` for now) then run playwright as part of another integration test action.

**Comment by alecthomas** [comment]
There is a [Go library for Playwright](https://github.com/playwright-community/playwright-go). We'll have to have a think about where to run these tests though, I assume we'll have a lot of Playwright tests, would each Playwright test correspond to a single integration tests? That might end up being quite slow.

We're going to want to improve the integration testing framework so that it reuses the existing controller without restarting everything, so perhaps once that exists we could do the above.

**Comment by wesbillman** [comment]
I think in the future we will definitely have many tests, yeah.  I don't think each test would correspond to a single integration test. In fact, I think for the foreseeable future, we can have all the tests run as a single integration test. If that becomes an issue we can shard them out later. 

That's how things are working here now. We start the controller once, then start running all the tests against the running controller. I also want to run the "default" FTL examples (`ftl dev --recreate`) with this, and probably switch to just running the exemplar once that is ready. Verses having a dedicated set of `testdata` for the playwright stuff. This way we can stay in sync with our exemplar and get a representative system for freeeeee :)
