### ISSUE TITLE
panic in pubsub lib Topic

### ISSUE THREAD

**Issue by wesbillman** [TBD54566975/ftl#2554]
Running `just e2e-frontend` in CI is getting a panic here: https://github.com/TBD54566975/ftl/actions/runs/10622270938/job/29446142300#step:6:1238

This command is running `ftl dev --recreate` under the hood.

```
panic: ack timeout

goroutine 180 [running]:
github.com/alecthomas/types/pubsub.(*Topic[...]).run(0x2203100)
	/home/runner/go/pkg/mod/github.com/alecthomas/types@v0.16.0/pubsub/pubsub.go:197 +0x6cb
created by github.com/alecthomas/types/pubsub.New[...] in goroutine 127
/home/runner/go/pkg/mod/github.com/alecthomas/types@v0.16.0/pubsub/pubsub.go:67
```

Note: this is not necessarily part of FTL's pubsub feature. It is caused by something using @alecthomass pubsub library

**Comment by matt2e** [comment]
This happened in production at Aug 29, 2024 at 2:10:40.517 pm AEST
This happened 38s after the first occurence of this issue on the same controller: https://github.com/TBD54566975/ftl/issues/2539
The second time we saw that other issue, it was was not followed by this issue. Possibly because they are unrelated, or because that controller's pubsub set up was broken so subsequent issues didn't cause a similar panic.

production logs:
```
panic: ack timeout
goroutine 31 [running]:
github.com/alecthomas/types/pubsub.(*Topic[...]).run(0x1cf3dc0)
/root/go/pkg/mod/github.com/alecthomas/types@v0.16.0/pubsub/pubsub.go:197 +0x6cb
created by github.com/alecthomas/types/pubsub.New[...] in goroutine 1
/root/go/pkg/mod/github.com/alecthomas/types@v0.16.0/pubsub/pubsub.go:67 +0x10e
```

**Comment by matt2e** [comment]
line in the lib: https://github.com/alecthomas/types/blob/92ffae5908acce44483cd09ed1c7918fea61f7d8/pubsub/pubsub.go#L197

We use the lib in a few places, but judging from the linked CI logs, it could be:
- `DAL.DeploymentChanges` https://github.com/TBD54566975/ftl/blob/main/backend/controller/dal/dal.go#L244
- `buildengine.schemaChanges` https://github.com/TBD54566975/ftl/blob/main/internal/buildengine/engine.go#L73

I don't think it can be `configuration.cache` as I don't think thatd be used in the integration test.
