### ISSUE TITLE
Set up a new console endpoint to eventually serve both `useModules` and `useSchema` console use cases

### ISSUE THREAD

**Issue by deniseli** [TBD54566975/ftl#2805]
Currently, we have two separate endpoints, one on the console service and one on the controller service, that both provide _most_ of the data we need. We can't standardize to just one of those two because they're each missing data that only the other contains. We should just build a new endpoint that actually includes everything, formatted correctly, so we don't need to do this going forward.

Also, the new one needs to include the `builtin` module.

**Comment by wesbillman** [comment]
We'll probably want a dedicated `StreamModules` rpc in console service so we can live update the tree and the rest of the app as needed.

That might look something like this, and would replace `PullSchema` (which lives on the `controller` service now).
```proto
rpc StreamModules(StreamModulesRequest) returns (stream StreamModulesResponse);
```

The response here would be lighter weight than the `PullSchema` since we only really need enough data to build the module tree and provide data to dedicated decl pages. This will also let us control what the `Module` looks like to the frontend.
